model:
  base_learning_rate: 1.e-2
  target: ldm.models.downstream.efficient_subclass.EfficientSubclassSegmentation
  params:
    monitor: val/loss
    n_coarse: 2
    n_fine: 4
    unet_config:
      # target: ldm.modules.diffusionmodules.model.Model
      # params:
      #   ch: 16
      #   out_ch: 16
      #   ch_mult: [1, 2, 4, 8]
      #   num_res_blocks: 2
      #   attn_resolutions: []
      #   dropout: .3
      #   in_channels: 4
      #   resolution: 96
      #   use_timestep: false 
      #   attn_type: 'none'
      #   dims: 3
      target: ldm.modules.backbones.modules.UNetModel
      params:
        input_channels: 4
        dims: 3

    use_data_augmentation: 0 
    use_mixup: 1 
    use_ldm_mixup: 0 
    use_pseudo: 1 
    use_separate_normalization: 0 
    use_prior_concatenation: 0 
    mixup_alphas: .5

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    wrap: False
    batch_sampler: 
      target: 
        inference.utils.DistributedTwoStreamBatchSampler
      params:
        primary_batch_size: 2
        iterate_on_primary_indices: true
    train:
      target: ldm.data.brats2021.BraTS2021_DA
      params:
        split: train
        n_fine: 10
        crop_to: [96, 96, 96]
        base: /ailab/user/dailinrui/data/datasets/BraTS2021
    validation:
      target: ldm.data.brats2021.BraTS2021_DA
      params:
        split: val
        n_fine: null
        crop_to: [96, 96, 96]
        base: /ailab/user/dailinrui/data/datasets/BraTS2021

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 100
        val_batch_frequency: 20
        max_images: 10
        log_on_batch_idx: true
        logger:
          inputs: 
            target: image_rescale
          seg_fine:
            target: mask_rescale
            params: 
              n_mask: 4
          seg_coarse:
            target: mask_rescale
            params: 
              n_mask: 2
          gt_fine:
            target: mask_rescale
            params: 
              n_mask: 4
          gt_coarse:
            target: mask_rescale
            params: 
              n_mask: 2

  trainer:
    benchmark: True
    max_steps: 40000
    replace_sampler_ddp: false