model:
  base_learning_rate: 2.e-5
  target: ldm.models.diffusion.cdpm.CategoricalDiffusion
  params:
    linear_start: 1e-2
    linear_end: 0.2
    timesteps: 1000
    num_classes: 4  # include background class
    mask_key: fine
    conditioning_key: null
    concat_key: null
    crossattn_key: null
    monitor: val/loss
    ckpt_path: /ailab/user/dailinrui/data/ldm/brats21_cdm_128_128_128_coarse/checkpoints/last-v1.ckpt
    ignore_keys: [model.diffusion_model.input_blocks.0.0.weight, model.diffusion_model.input_blocks.0.0.bias, model.diffusion_model.out.2.weight, model.diffusion_model.out.2.bias]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 4
        out_channels: 4
        image_size: [128, 128, 128]
        model_channels: 64
        attention_resolutions: [8, 16]
        num_res_blocks: 1
        channel_mult: [1, 1, 2, 2, 4]
        # use_spatial_transformer: true
        # context_dim: 768
        num_heads: 1
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    concat_encoder_config: 
      target: torch.nn.Identity

    crossattn_encoder_config:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: train
        resize_to: [128, 128, 128]
        no_mask_normalize: true
        max_size: 10
    validation:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: val
        resize_to: [128, 128, 128]
        no_mask_normalize: true
        max_size: 5

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 1
        val_batch_frequency: 1
        max_images: 10
        logger:
          inputs: 
            target: mask_rescale
            params: 
              n_mask: 4
          noise:
            target: mask_rescale
            params: 
              n_mask: 4
          samples:
            target: mask_rescale
            params: 
              n_mask: 4

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_epochs: 1000