model:
  base_learning_rate: 2.e-5
  target: ldm.models.diffusion.cdpm.CategoricalDiffusionV2
  params:
    linear_start: 1e-2
    linear_end: 0.2
    timesteps: 1000
    num_classes: 20  # include background class
    mask_key: totalseg
    conditioning_key: crossattn
    concat_key: null
    crossattn_key: prompt_context
    monitor: val/loss

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 20
        out_channels: 20
        image_size: [128, 128, 128]
        model_channels: 64
        attention_resolutions: [8, 16]
        num_res_blocks: 1
        channel_mult: [1, 1, 2, 2, 4]
        use_spatial_transformer: true
        context_dim: 768
        num_heads: 1
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    concat_encoder_config: 
      target: torch.nn.Identity

    crossattn_encoder_config:
      target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    wrap: false
    train:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: train
        resize_to: [128, 128, 128]
    validation:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: val
        resize_to: [128, 128, 128]
        max_size: 5

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        val_batch_frequency: 1
        max_images: 10
        logger:
          inputs: 
            target: mask_rescale
            params: 
              n_mask: 20
          noise:
            target: mask_rescale
            params: 
              n_mask: 20
          samples:
            target: mask_rescale
            params: 
              n_mask: 20

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_epochs: 1000