model:
  base_learning_rate: 5e-5
  target: inference.models.InferCategoricalDiffusion
  params:
    linear_start: 1e-2
    linear_end: 0.2
    log_every_t: 200
    timesteps: 1000
    num_classes: 12  # include background class
    data_key: mask
    cond_key: context
    conditioning_key: crossattn
    monitor: val/lpips_metric_epoch
    cond_stage_trainable: false
    use_automatic_optimization: false
    class_weights: [1,1,1,1,1,1,1,1,1,1,1,1]
    # use or not use legacy from ccdm.git
    # use_legacy: true
    # parameterization: kl , 
    # ckpt_path: /ailab/user/dailinrui/data/ccdm/ruijin_ccdm_64_128_128_baseline/checkpoint/checkpoint_ep64_gs168155.ckpt
    use_legacy: false
    parameterization: x0
    ckpt_path: /ailab/user/dailinrui/data/ldm/ruijin_cdm_96_192_192_x0_v3/checkpoints/last-v1.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.CCDMUNetModel
      params:
        image_size: [64, 128, 128]
        in_channels: 12
        out_channels: 12
        model_channels: 64
        attention_resolutions: [32, 16, 8]
        num_res_blocks: 2
        channel_mult: [1,2,4,4,8]
        use_spatial_transformer: true
        context_dim: 5120
        num_heads: 1
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt
        use_label_predictor: false
        n_labels: 6

    cond_stage_config: 
      target: torch.nn.Identity

    loss_config:
      # ce_loss:
      #   coeff: 10
      kl_div:
        coeff: 1
      dir_loss:
        coeff: 1

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 12
    wrap: false
    test:
      target: ldm.data.ruijin.Ruijin_3D
      params:
        split: test
        resize_to: [64, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: 10
        log_images_kwargs:
          verbose: true
          plot_denoising_rows: true
          plot_progressive_rows: true
        logger:
          inputs: 
            target: mask_rescale
            params: 
              n_mask: 11
          noise:
            target: mask_rescale
            params: 
              n_mask: 11
          samples:
            target: mask_rescale
            params: 
              n_mask: 11

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_epochs: 1000