model:
  base_learning_rate: 1e-4
  target: inference.models.InferMixedAutoencoderVQ
  params:
    monitor: "val/rec_loss"
    image_key: image
    cond_key: coarse
    embed_dim: 4
    n_embed: 8192
    dims: 3
    is_conditional: true
    lossconfig:
      target: torch.nn.Identity

    ckpt_path: /ailab/user/dailinrui/data/ldm/brats21fg_cvq_64_64_64/checkpoints/last.ckpt

    ddconfig:
      double_z: False
      z_channels: 4
      resolution: [64, 64, 64]
      condition_channels: 1
      in_channels: 4
      out_ch: 4
      ch: 128
      ch_mult: [ 1, 2, 4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [4]
      dropout: 0.0
      dims: 3
      attn_type: vanilla
      use_checkpoint: True  # always use ckpt

    save_dataset: true 
    save_dataset_path: /ailab/user/dailinrui/data/ldm/brats21_ldm_cvq_128_128_128/dataset
    include_keys: [image, label, premix, premix_label, mixed_samples, mixed_fine]
    suffix_keys: 
      data: .h5

    eval_scheme: [1, 3]

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: False
    batch_sampler: 
      target: 
        inference.utils.TwoStreamBatchSampler
      params:
        primary_batch_size: 1
        iterate_on_primary_indices: false 
    test:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        n_fine: 10
        split: train
        crop_to: [128, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: -1
        log_separate: false
        clamp: false
        log_images_kwargs:
          verbose: true
          alpha: .2
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 3
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    replace_sampler_ddp: false

