model:
  base_learning_rate: 1e-4
  target: ldm.models.autoencoder.VQModel
  params:
    monitor: "val/rec_loss"
    image_key: image
    embed_dim: 4
    n_embed: 8192
    dims: 3
    lossconfig:
      target: ldm.modules.losses.VQLPIPSWithDiscriminator
      params:
        disc_start: 50001
        disc_weight: 0.5
        n_classes: 8192  # =n_embed
        gan_feat_weight: 0.
        nframes_select: 1  # 1 as in medicaldiffusion

    ddconfig:
      double_z: false
      z_channels: 4
      resolution: [128, 128, 128]
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1, 1, 1 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      dims: 3
      attn_type: none
      use_checkpoint: True  # always use ckpt

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.ensemble.EnsembleDataset
      params:
        split: train
        resize_to: [128, 128, 128]
    validation:
      target: ldm.data.ensemble.EnsembleDataset
      params:
        split: val
        resize_to: [128, 128, 128]
        max_size: 200

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      max_images: 10
      log_separate: false
      params:
        train_batch_frequency: 400
        max_images: 8
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    accumulate_grad_batches: 1

