model:
  base_learning_rate: 2.e-5
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    image_key: image
    embed_dim: 8
    dims: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 20001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1
        gan_feat_weight: 0.

    ddconfig:
      double_z: true
      z_channels: 4
      resolution: [128, 128, 128]
      in_channels: 1
      out_ch: 1
      ch: 96
      ch_mult: [ 1, 1, 1 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      dropout: 0.0
      attn_resolutions: []  # on z axis, starting with 8->16->32 for len(ch_mult)==4 and resolution==64
      attn_type: none

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 12
    wrap: False
    train:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: train
        resize_to: [128, 128, 128]
    validation:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: val
        resize_to: [128, 128, 128]
        max_size: 200

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        log_separate: false
        train_batch_frequency: 400
        val_batch_frequency: 20
        max_images: 5
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
