model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModel
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    n_embed: 16384
    dims: 2
    lossconfig:
      target: ldm.modules.losses.VQLPIPSWithDiscriminator
      params:
        dims: 2
        disc_start: 50001
        disc_weight: 0.5
        gan_feat_weight: 0
        n_classes: 16384  # =n_embed

    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [32]
      dropout: 0.0
      dims: 2

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    wrap: True
    train:
      target: ldm.data.ruijin.AutoencoderDataset
      params:
        split: train
    validation:
      target: ldm.data.ruijin.AutoencoderDataset
      params:
        split: val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
