model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    image_key: mask
    embed_dim: 4
    dims: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1
        gan_feat_weight: 0

    ddconfig:
      double_z: True
      z_channels: 1
      resolution: [96, 192, 192]
      in_channels: 1
      out_ch: 1
      ch: 96
      ch_mult: [1,2,4,4,8]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      dropout: 0.0
      attn_resolutions: [8,]  # on z axis, starting with 8->16->32 for len(ch_mult)==4 and resolution==64
      attn_type: vanilla
      use_checkpoint: True  # always use ckpt

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.ruijin.Ruijin_3D
      params:
        split: train
        resize_to: [64, 128, 128]
    validation:
      target: ldm.data.ruijin.Ruijin_3D
      params:
        split: val
        resize_to: [64, 128, 128]


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 2000
        max_images: 8
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    max_epochs: 1000