model:
  base_learning_rate: 4.5e-7
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    image_key: mask
    embed_dim: 4
    dims: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1
        gan_feat_weight: 0
        dims: 3

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 1 # should be 1, but now it is 3, broadcast along channel dim
      out_ch: 1
      ch: 32
      ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      dropout: 0.0
      dims: 3
      attn_resolutions: [32, 16, 8]

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    wrap: False
    train:
      target: ldm.data.ruijin_3d.AutoencoderDataset
      params:
        split: train
    validation:
      target: ldm.data.ruijin_3d.AutoencoderDataset
      params:
        split: val

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
