model:
  base_learning_rate: 2e-5
  train_target: ldm.models.autoencoder.VQModel
  test_target: inference.models.InferAutoencoderVQ
  params:
    monitor: "val/rec_loss"
    image_key: $key
    embed_dim: 8
    n_embed: 8192
    dims: 3
    lossconfig:
      target: ldm.modules.losses.VQLPIPSWithDiscriminator
      params:
        disc_start: 20001
        disc_weight: 0.5
        n_classes: 8192  # =n_embed
        gan_feat_weight: 1.
        nframes_select: 1  # 1 as in medicaldiffusion

    ddconfig:
      double_z: false
      z_channels: 8
      resolution: [128, 128, 128]
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1, 1, 1 ]  
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      dims: 3
      attn_type: none

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.base.SimpleDataset
      params:
        split: train
        patch_size: [128, 128, 128]
        any_dict: 
          image: $path
          label: $path
    validation:
      target: ldm.data.base.SimpleDataset
      params:
        split: val
        patch_size: [128, 128, 128]
        max_size: 200
    test:
      target: ldm.data.base.SimpleDataset
      params:
        split: test
        patch_size: [128, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: true
    accumulate_grad_batches: 1
    limit_test_batches: 100

