model:
  base_learning_rate: 2.0e-05
  target: inference.models.InferMixedDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: coarse
    conditioning_key: concat
    image_size: [128, 128, 128]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    mix_scheme: direct
    ckpt_path: /ailab/user/dailinrui/data/ldm/brats21_ddpm_128_128_128/checkpoints/epoch=000955.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128  # not used
        in_channels: 5
        out_channels: 4
        model_channels: 32
        attention_resolutions: [32, 16, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4, 8]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config: 
      target: ldm.modules.encoders.modules.IdentityFirstStage

    cond_stage_config: __is_first_stage__

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: False
    batch_sampler: 
      target: 
        inference.utils.TwoStreamBatchSampler
      params:
        primary_batch_size: 1
    test:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: train
        n_fine: 10
        crop_to: [128, 128, 128]
        base: /ailab/user/dailinrui/data/datasets/BraTS2021

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: -1
        log_separate: false
        log_original: true
        log_original_keys: [mixed_samples, mixed_fine, mixed_coarse]
        log_images_kwargs:
          verbose: true
          log_metrics: true
          ddim_steps: null
          log_group_metrics_in_2d: true
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 1
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    replace_sampler_ddp: false
    max_epochs: 1000
