model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.Img2MaskDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1
    image_key: image
    cond_stage_key: coarse
    mask_key: fine
    conditioning_key: concat
    image_size: [8, 8, 8]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    vae_decoder_trainable: false
    ckpt_path: /ailab/user/dailinrui/data/ldm/static_brats21_ldm_cvae_kl_64_64_64/checkpoints/last.ckpt
    ignore_keys: [betas, alphas_cumprod, sqrt_alphas_cumprod, sqrt_one_minus_alphas_cumprod, log_one_minus_alphas_cumprod, sqrt_recip_alphas_cumprod, sqrt_recipm1_alphas_cumprod, posterior_variance, posterior_log_variance_clipped, posterior_mean_coef1, posterior_mean_coef2]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 12
        out_channels: 4
        model_channels: 128
        attention_resolutions: [32, 16, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config: 
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: "val/rec_loss"
        image_key: image
        cond_key: coarse
        embed_dim: 4
        is_conditional: true
        dims: 3
        ckpt_path: /ailab/user/dailinrui/data/ldm/static_brats21_cvae_kl_64_64_64/checkpoints/epoch=000871.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: True
          z_channels: 4
          resolution: [64, 64, 64]
          in_channels: 4
          condition_channels: 1
          out_ch: 4
          ch: 96
          ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          dropout: 0.0
          attn_resolutions: [8,]  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
          attn_type: vanilla
          use_checkpoint: True  # always use ckpt

    cond_stage_config: 
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: True
        z_channels: 4
        resolution: [64, 64, 64]
        in_channels: 1
        out_ch: 4
        ch: 96
        ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        dropout: 0.0
        attn_resolutions: [8,]  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
        attn_type: vanilla
        use_checkpoint: True  # always use ckpt

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: train
        crop_to: [64, 64, 64]
        max_size: 10
    validation:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: val
        crop_to: [64, 64, 64]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 1
        val_batch_frequency: 20
        max_images: 10
        log_images_kwargs:
          ddim_steps: null
        increase_log_steps: False
        log_on_batch_idx: true
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 3
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    max_epochs: 200