model:
  base_learning_rate: 2.0e-05
  target: inference.models.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: mask
    conditioning_key: concat
    image_size: [16, 16, 16]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    # mix_scheme: latent
    # ckpt_path: /ailab/user/dailinrui/data/ldm/brats21_ldm_cvq_128_128_128/checkpoints/epoch=000921.ckpt
    # mix_scheme: vq
    # ckpt_path: /ailab/user/dailinrui/data/ldm/brats21fg_cvq_64_64_64/checkpoints/last.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 8
        out_channels: 4
        model_channels: 128
        attention_resolutions: [4, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config: 
      target: ldm.models.autoencoder.VQModelInterface
      params:
        monitor: "val/rec_loss"
        image_key: image
        cond_key: coarse
        embed_dim: 4
        n_embed: 8192
        is_conditional: true
        dims: 3
        ckpt_path: /ailab/user/dailinrui/data/ldm/brats21_cvq_128_128_128/checkpoints/epoch=000181.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: false
          z_channels: 4
          resolution: [128, 128, 128]
          in_channels: 4
          condition_channels: 1
          out_ch: 4
          ch: 128
          ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          dropout: 0.0
          attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
          attn_type: none
          use_checkpoint: True  # always use ckpt

    cond_stage_config: 
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: false
        z_channels: 4
        resolution: [128, 128, 128]
        in_channels: 1
        out_ch: 4
        ch: 64
        ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        dropout: 0.0
        attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
        attn_type: none
        use_checkpoint: True  # always use ckpt

    save_dataset: true 
    save_dataset_path: /ailab/user/dailinrui/data/ldm/brats21_ldm_cvq_128_128_128/dataset
    include_keys: [image, label]
    suffix_keys: 
      image: .nii.gz
      label: .nii.gz

    eval_scheme: [1, 3]

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: False
    batch_sampler: 
      target: 
        inference.utils.TwoStreamBatchSampler
      params:
        primary_batch_size: 1
        iterate_on_primary_indices: false 
    test:
      # target: ldm.data.brats2021.BraTS2021_3D
      # params:
      #   n_fine: 10
      #   split: train
      #   crop_to: [128, 128, 128]
      target: ldm.data.base.GenDatasetForMSD
      params:
        crop_to: [128, 128, 128]
        gen_field: mask
        dummy_fields: [image, ]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 3
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale
          # samples_mixed:
          #   target: image_and_mask
          #   params:
          #     n_mask: 3

  trainer:
    benchmark: true
    replace_sampler_ddp: false
    max_epochs: 1