model:
  base_learning_rate: 2.0e-05
  target: inference.sampler.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: mask
    conditioning_key: concat
    image_size: [8, 8, 8]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    ckpt_path: /ailab/user/dailinrui/data/ldm/static_brats21_ldm_cvae_kl_64_64_64/checkpoints/last.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 12
        out_channels: 4
        model_channels: 128
        attention_resolutions: [32, 16, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config: 
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        monitor: "val/rec_loss"
        image_key: image
        cond_key: coarse
        embed_dim: 4
        is_conditional: true
        dims: 3
        ckpt_path: /ailab/user/dailinrui/data/ldm/static_brats21_cvae_kl_64_64_64/checkpoints/epoch=000871.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: True
          z_channels: 4
          resolution: [64, 64, 64]
          in_channels: 4
          condition_channels: 1
          out_ch: 4
          ch: 96
          ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          dropout: 0.0
          attn_resolutions: [8,]  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
          attn_type: vanilla
          use_checkpoint: True  # always use ckpt

    cond_stage_config: 
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: True
        z_channels: 4
        resolution: [64, 64, 64]
        in_channels: 1
        out_ch: 4
        ch: 96
        ch_mult: [1,2,4,4]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        dropout: 0.0
        attn_resolutions: [8,]  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
        attn_type: vanilla
        use_checkpoint: True  # always use ckpt

    test_scheme: mixup
    eval_scheme: [1, 3]

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: False
    test:
      target: ldm.data.brats2021.BraTS2021_3D
      params:
        split: test
        crop_to: [64, 64, 64]

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: 4
        log_separate: true
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 3
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale
          # samples_mixed:
          #   target: image_and_mask
          #   params:
          #     n_mask: 3

  trainer:
    benchmark: True
    max_epochs: 1000