model:
  base_learning_rate: 2.0e-05
  target: inference.models.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: image
    conditioning_key: concat
    image_size: [32, 32, 32]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    ckpt_path: /ailab/user/dailinrui/data/ldm/ensemble_ldm_vq_128_128_128/checkpoints/last.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 8
        out_channels: 4
        model_channels: 128
        attention_resolutions: [4, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        monitor: "val/rec_loss"
        image_key: image
        embed_dim: 4
        n_embed: 8192
        dims: 3
        ckpt_path: /ailab/user/dailinrui/data/ldm/ensemble_vq_128_128_128/checkpoints/last.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: false
          z_channels: 4
          resolution: [128, 128, 128]
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1, 1, 1 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          dims: 3
          attn_type: none
          use_checkpoint: True  # always use ckpt

    cond_stage_config: 
      target: ldm.modules.diffusionmodules.model.Encoder
      params:
        double_z: false
        z_channels: 4
        resolution: [128, 128, 128]
        in_channels: 1
        ch: 64
        out_ch: 1
        ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
        num_res_blocks: 2
        dropout: 0.0
        attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
        attn_type: none
        use_checkpoint: true  # always use ckpt

    save_dataset: true 
    save_dataset_path: /ailab/user/dailinrui/data/ldm/ensemble_ldm_vq_128_128_128/dataset
    include_keys: [samples, inputs, conditioning]
    suffix_keys: 
      samples: .nii.gz
      inputs: .nii.gz
      conditioning: .nii.gz
    
    eval_scheme: [1, 2, 3]

data:
  target: test.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: false
    test:
      target: ldm.data.base.GeneratedDataset
      params:
        split: all
        base_folder: /ailab/user/dailinrui/data/ccdm/ensemble_128_128_128_baseline/dataset
        max_size: null

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: -1
        log_separate: false
        log_images_kwargs:
          verbose: false
          log_metrics: true
          log_group_metrics_in_2d: true
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 15
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale
          conditioned_samples:
            target: image_and_mask
            params:
              n_mask: 15

  trainer:
    benchmark: True