model:
  base_learning_rate: 2.e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: 
      crossattn: prompt_context
      concat: cond
    conditioning_key: hybrid
    # only text cond
    # cond_stage_key: prompt_context
    # conditioning_key: crossattn
    image_size: [32, 32, 32]  # after first-stage encoding
    channels: 8  # after first-stage encoding
    monitor: val/loss_simple
    cond_stage_trainable: true
    use_ema: false
    use_window_norm: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 12
        out_channels: 8
        model_channels: 128
        attention_resolutions: [2, 4]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 64
        use_checkpoint: true  # always use ckpt
        use_spatial_transformer: true
        context_dim: 768

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        monitor: "val/rec_loss"
        image_key: image
        embed_dim: 8
        n_embed: 8192
        dims: 3
        # no cam
        ckpt_path: /ailab/user/dailinrui/data/ldm/ensemble_norm1000_vq_128_128_128/checkpoints/last.ckpt
        # ckpt_path: /ailab/user/dailinrui/data/ldm/ensemblev2_vq_norm2400_128_128_128/checkpoints/last.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: false
          z_channels: 8
          resolution: [128, 128, 128]
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [ 1, 1, 1 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          dims: 3
          attn_type: none

    cond_stage_config: 
      # guidegen
      target: ldm.modules.encoders.modules.HybridConditionEncoder
      params:
        concat_module:
          target: ldm.modules.diffusionmodules.model.Encoder
          params:
            double_z: false
            z_channels: 4
            resolution: [128, 128, 128]
            in_channels: 2
            ch: 64
            out_ch: 1
            ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
            num_res_blocks: 1
            dropout: 0.0
            attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
            attn_type: none
        crossattn_module:
          target: torch.nn.Identity
      
      # only mask cond
      # target: ldm.modules.diffusionmodules.model.Encoder
      # params:
      #   double_z: false
      #   z_channels: 4
      #   resolution: [128, 128, 128]
      #   in_channels: 2
      #   ch: 64
      #   out_ch: 1
      #   ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
      #   num_res_blocks: 1
      #   dropout: 0.0
      #   attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
      #   attn_type: none

      # only text cond
      # target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
    wrap: False
    train:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: train
        resize_to: [128, 128, 128]
    validation:
      target: ldm.data.ensemble_v2.GatheredDatasetForGeneration
      params:
        split: val
        resize_to: [128, 128, 128]
        max_size: 50

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 400
        max_images: 10
        log_images_kwargs:
          quantize_denoised: false 
          plot_conditioned_samples: false
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    max_epochs: 1000