model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: data
    cond_stage_key: text
    conditioning_key: crossattn
    image_size: 
      - 64
      - 128
      - 128
    channels: 2
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 2
        out_channels: 1
        model_channels: 64
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 32
        - 16
        - 8
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 2
        - 4
        - 5
        num_head_channels: 32
    first_stage_config: 
      target: torch.nn.Identity
    cond_stage_config: 
      target: ldm.modules.encoders.modules.FrozenBERTEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.ruijin_3d.AutoencoderDataset
      params:
        split: train
    validation:
      target: ldm.data.ruijin_3d.AutoencoderDataset
      params:
        split: val


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True