model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: mask
    cond_stage_key: text
    conditioning_key: crossattn
    image_size: 
      - 64
      - 128
      - 128
    channels: 1
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        dims: 3
        image_size: 64  # not used
        in_channels: 1
        out_channels: 1
        model_channels: 64
        attention_resolutions: [32, 16, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 2, 4, 8]
        num_head_channels: 32
        use_checkpoint: True  # always use ckpt

    first_stage_config: 
      target: ldm.modules.encoders.modules.DummyFirstStage

    cond_stage_config: 
      target: ldm.modules.encoders.modules.FrozenBERTEmbedder
      # params:
      #   ckpt_path: /mnt/data/oss_beijing/dailinrui/data/pretrained_weights/bert-ernie-health

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.ruijin.Ruijin_3D
      params:
        split: train
        resize_to: [64, 128, 128]
    validation:
      target: ldm.data.ruijin.Ruijin_3D
      params:
        split: val
        resize_to: [64, 128, 128]


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 2000
        max_images: 4
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: mask_rescale
            params: 
              n_mask: 11
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    max_epochs: 1000