model:
  base_learning_rate: 1e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: mask
    image_size: 64
    channels: 4
    dims: 2
    monitor: val/loss_simple_ema
    advance_step: 3

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        dims: 2
        image_size: 512
        in_channels: 8
        out_channels: 4
        model_channels: 96
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        - 5
        num_head_channels: 32
    first_stage_config: #__is_no_first_stage__
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: /mnt/workspace/dailinrui/data/pretrained/ldm/static_ae_kl_ruijin_512x512_fullimage_windownorm/checkpoints/last.ckpt
        embed_dim: 4
        monitor: "val/rec_loss"
        dims: 2
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          dropout: 0.0
          dims: 2
          attn_resolutions:
          - 16
          - 8
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: 
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        ckpt_path: /mnt/workspace/dailinrui/data/pretrained/ldm/static_ae_ruijin_pimage_and_mask_cond/checkpoints/last.ckpt
        embed_dim: 4
        monitor: "val/rec_loss"
        dims: 2
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 512
          in_channels: 2
          out_ch: 2
          ch: 160
          ch_mult: [ 1,2,4,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          dropout: 0.0
          dims: 2
          attn_resolutions: [16,8]
        lossconfig:
          target: torch.nn.Identity
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.ruijin_pimage_and_mask.PretrainDataset
      params:
        split: train
        toy: false
    validation:
      target: ldm.data.ruijin_pimage_and_mask.PretrainDataset
      params:
        split: val
        toy: false


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 4000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True