model:
  base_learning_rate: 1.e-4
  train_target: ldm.models.diffusion.ddpm.LatentDiffusion
  test_target: inference.models.InferLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: label
    conditioning_key: concat
    image_size: [64, 64, 64]  # after first-stage encoding
    channels: 4               # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        in_channels: 5
        out_channels: 4
        model_channels: 128
        attention_resolutions: []
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt

    first_stage_config:
      # no loss needed
      lossconfig:
        target: nn.Identity
      # copy the following from vq model
      ddconfig:
        double_z: false
        z_channels: 8
        resolution: [128, 128, 128]
        in_channels: 1
        out_ch: 1
        ch: 128
        ch_mult: [ 1, 1, 1 ]  
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
        dims: 3
        attn_type: none

    cond_stage_config: 
      target: ldm.modules.encoders.modules.ResizeConditionEncoder
      params:
        input_size: [128, 128, 128]
        output_size: [64, 64, 64]
        resize_mode: nearest

  test_only_params:
    ckpt_path: $path
    save_dataset: true 
    save_dataset_path: $path
    suffix_keys: 
      samples: .nii.gz
      mask: .nii.gz

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: False
    train:
      target: ldm.data.base.SimpleDataset
      params:
        split: train
        patch_size: [128, 128, 128]
    validation:
      target: ldm.data.base.SimpleDataset
      params:
        split: val
        patch_size: [128, 128, 128]
        max_size: 50
    test:
      target: ldm.data.base.SimpleDataset
      params:
        split: test
        patch_size: [128, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs: 
          ddim_steps: 50
        logger:
          inputs: 
            target: image_rescale
          conditioning:
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: true
    max_epochs: 1000
    replace_sampler_ddp: false
    limit_test_batches: 500